//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    
    public partial class ChiPhiSanXuat
    {
        public ChiPhiSanXuat()
        {
            this.PTVATTUKEHOACH = 0m;
            this.PTTAISANKEHOACH = 0m;
            this.PTNHANCONGKEHOACH = 0m;
            this.PTVATTUTHUCHIEN = 0m;
            this.PTTAISANTHUCHIEN = 0m;
            this.PTNHANCONGTHUCHIEN = 0m;
        }
    
        public Nullable<System.DateTime> NGAY { get; set; }
        public string CONGDOAN { get; set; }
        public Nullable<decimal> PTVATTUKEHOACH { get; set; }
        public Nullable<decimal> PTTAISANKEHOACH { get; set; }
        public Nullable<decimal> PTNHANCONGKEHOACH { get; set; }
        public Nullable<decimal> PTVATTUTHUCHIEN { get; set; }
        public Nullable<decimal> PTTAISANTHUCHIEN { get; set; }
        public Nullable<decimal> PTNHANCONGTHUCHIEN { get; set; }
    }
}
