//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    
    public partial class CountStatus
    {
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> SLCH { get; set; }
        public string STATUS { get; set; }
    }
}
