//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    
    public partial class ThongKeLaoDong
    {
        public Nullable<System.DateTime> Ngay { get; set; }
        public string CongDoan { get; set; }
        public decimal DiLam { get; set; }
        public decimal Tongld { get; set; }
        public decimal TyLeVang { get; set; }
    }
}
