//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TKTDSXEntities : DbContext
    {
        public TKTDSXEntities()
            : base("name=TKTDSXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ZEMP_CONGDOAN> ZEMP_CONGDOAN { get; set; }
        public virtual DbSet<ZEMP_CH> ZEMP_CH { get; set; }
        public virtual DbSet<ZEMP_DAURA_KV> ZEMP_DAURA_KV { get; set; }
        public virtual DbSet<ZEMP_DAURA_NG> ZEMP_DAURA_NG { get; set; }
        public virtual DbSet<ZEMP_DAURA_WC> ZEMP_DAURA_WC { get; set; }
        public virtual DbSet<ZEMP_KV> ZEMP_KV { get; set; }
        public virtual DbSet<ZEMP_NG> ZEMP_NG { get; set; }
        public virtual DbSet<ZEMP_PQ> ZEMP_PQ { get; set; }
        public virtual DbSet<ZEMP_SL_CH> ZEMP_SL_CH { get; set; }
        public virtual DbSet<ZEMP_SL_KV> ZEMP_SL_KV { get; set; }
        public virtual DbSet<ZEMP_SL_NG> ZEMP_SL_NG { get; set; }
        public virtual DbSet<ZEMP_SL_WC> ZEMP_SL_WC { get; set; }
        public virtual DbSet<ZEMP_TK_KV> ZEMP_TK_KV { get; set; }
        public virtual DbSet<ZEMP_TK_NG> ZEMP_TK_NG { get; set; }
        public virtual DbSet<ZEMP_TK_WC> ZEMP_TK_WC { get; set; }
        public virtual DbSet<ZEMP_USER> ZEMP_USER { get; set; }
        public virtual DbSet<ZEMP_WC> ZEMP_WC { get; set; }
        public virtual DbSet<ZEMP_CF_MODE> ZEMP_CF_MODE { get; set; }
        public virtual DbSet<ZEMP_LOG> ZEMP_LOG { get; set; }
    
        public virtual ObjectResult<SanLuongOnlineReturn> GetSanLuongOnline(string systemId, string mode, string capdo, string giatricapdo, string congdoan, string ngay)
        {
            var systemIdParameter = systemId != null ?
                new ObjectParameter("SystemId", systemId) :
                new ObjectParameter("SystemId", typeof(string));
    
            var modeParameter = mode != null ?
                new ObjectParameter("mode", mode) :
                new ObjectParameter("mode", typeof(string));
    
            var capdoParameter = capdo != null ?
                new ObjectParameter("capdo", capdo) :
                new ObjectParameter("capdo", typeof(string));
    
            var giatricapdoParameter = giatricapdo != null ?
                new ObjectParameter("giatricapdo", giatricapdo) :
                new ObjectParameter("giatricapdo", typeof(string));
    
            var congdoanParameter = congdoan != null ?
                new ObjectParameter("congdoan", congdoan) :
                new ObjectParameter("congdoan", typeof(string));
    
            var ngayParameter = ngay != null ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SanLuongOnlineReturn>("GetSanLuongOnline", systemIdParameter, modeParameter, capdoParameter, giatricapdoParameter, congdoanParameter, ngayParameter);
        }
    
        public virtual ObjectResult<SelectListReturn> GetListCapDo(string systemId, string username)
        {
            var systemIdParameter = systemId != null ?
                new ObjectParameter("SystemId", systemId) :
                new ObjectParameter("SystemId", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectListReturn>("GetListCapDo", systemIdParameter, usernameParameter);
        }
    
        public virtual ObjectResult<SelectListReturn> GetListGiaTriCapDo(string systemId, string username, string capdo)
        {
            var systemIdParameter = systemId != null ?
                new ObjectParameter("SystemId", systemId) :
                new ObjectParameter("SystemId", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var capdoParameter = capdo != null ?
                new ObjectParameter("capdo", capdo) :
                new ObjectParameter("capdo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectListReturn>("GetListGiaTriCapDo", systemIdParameter, usernameParameter, capdoParameter);
        }
    
        public virtual ObjectResult<SelectListReturn> GetCongDoanLiveboard(string systemId)
        {
            var systemIdParameter = systemId != null ?
                new ObjectParameter("SystemId", systemId) :
                new ObjectParameter("SystemId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectListReturn>("GetCongDoanLiveboard", systemIdParameter);
        }
    
        public virtual ObjectResult<SelectListReturn> GetModeView(string systemId)
        {
            var systemIdParameter = systemId != null ?
                new ObjectParameter("SystemId", systemId) :
                new ObjectParameter("SystemId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectListReturn>("GetModeView", systemIdParameter);
        }
    
        public virtual ObjectResult<KHTHReturn> GetKeHoachThucHien(string systemId, string capDo, string giaTriCapDo, string congDoan, string fromDate, string toDate)
        {
            var systemIdParameter = systemId != null ?
                new ObjectParameter("systemId", systemId) :
                new ObjectParameter("systemId", typeof(string));
    
            var capDoParameter = capDo != null ?
                new ObjectParameter("capDo", capDo) :
                new ObjectParameter("capDo", typeof(string));
    
            var giaTriCapDoParameter = giaTriCapDo != null ?
                new ObjectParameter("giaTriCapDo", giaTriCapDo) :
                new ObjectParameter("giaTriCapDo", typeof(string));
    
            var congDoanParameter = congDoan != null ?
                new ObjectParameter("congDoan", congDoan) :
                new ObjectParameter("congDoan", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KHTHReturn>("GetKeHoachThucHien", systemIdParameter, capDoParameter, giaTriCapDoParameter, congDoanParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<CountStatus> CountTrangThaiChuyen(string systemId, string capDo, string giaTriCapDo, string congDoan, string fromDate, string toDate)
        {
            var systemIdParameter = systemId != null ?
                new ObjectParameter("systemId", systemId) :
                new ObjectParameter("systemId", typeof(string));
    
            var capDoParameter = capDo != null ?
                new ObjectParameter("capDo", capDo) :
                new ObjectParameter("capDo", typeof(string));
    
            var giaTriCapDoParameter = giaTriCapDo != null ?
                new ObjectParameter("giaTriCapDo", giaTriCapDo) :
                new ObjectParameter("giaTriCapDo", typeof(string));
    
            var congDoanParameter = congDoan != null ?
                new ObjectParameter("congDoan", congDoan) :
                new ObjectParameter("congDoan", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CountStatus>("CountTrangThaiChuyen", systemIdParameter, capDoParameter, giaTriCapDoParameter, congDoanParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<ChiPhiSanXuat> GETCHIPHISANXUAT(string sYSTEMID, string cAPDO, string gIATRICAPDO, string cONGDOAN, string fROMDATE, string tODATE)
        {
            var sYSTEMIDParameter = sYSTEMID != null ?
                new ObjectParameter("SYSTEMID", sYSTEMID) :
                new ObjectParameter("SYSTEMID", typeof(string));
    
            var cAPDOParameter = cAPDO != null ?
                new ObjectParameter("CAPDO", cAPDO) :
                new ObjectParameter("CAPDO", typeof(string));
    
            var gIATRICAPDOParameter = gIATRICAPDO != null ?
                new ObjectParameter("GIATRICAPDO", gIATRICAPDO) :
                new ObjectParameter("GIATRICAPDO", typeof(string));
    
            var cONGDOANParameter = cONGDOAN != null ?
                new ObjectParameter("CONGDOAN", cONGDOAN) :
                new ObjectParameter("CONGDOAN", typeof(string));
    
            var fROMDATEParameter = fROMDATE != null ?
                new ObjectParameter("FROMDATE", fROMDATE) :
                new ObjectParameter("FROMDATE", typeof(string));
    
            var tODATEParameter = tODATE != null ?
                new ObjectParameter("TODATE", tODATE) :
                new ObjectParameter("TODATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiPhiSanXuat>("GETCHIPHISANXUAT", sYSTEMIDParameter, cAPDOParameter, gIATRICAPDOParameter, cONGDOANParameter, fROMDATEParameter, tODATEParameter);
        }
    
        public virtual ObjectResult<ThongKeLaoDong> GetThongKeLaoDong(string sYSTEMID, string cAPDO, string gIATRICAPDO, string cONGDOAN, string fROMDATE, string tODATE)
        {
            var sYSTEMIDParameter = sYSTEMID != null ?
                new ObjectParameter("SYSTEMID", sYSTEMID) :
                new ObjectParameter("SYSTEMID", typeof(string));
    
            var cAPDOParameter = cAPDO != null ?
                new ObjectParameter("CAPDO", cAPDO) :
                new ObjectParameter("CAPDO", typeof(string));
    
            var gIATRICAPDOParameter = gIATRICAPDO != null ?
                new ObjectParameter("GIATRICAPDO", gIATRICAPDO) :
                new ObjectParameter("GIATRICAPDO", typeof(string));
    
            var cONGDOANParameter = cONGDOAN != null ?
                new ObjectParameter("CONGDOAN", cONGDOAN) :
                new ObjectParameter("CONGDOAN", typeof(string));
    
            var fROMDATEParameter = fROMDATE != null ?
                new ObjectParameter("FROMDATE", fROMDATE) :
                new ObjectParameter("FROMDATE", typeof(string));
    
            var tODATEParameter = tODATE != null ?
                new ObjectParameter("TODATE", tODATE) :
                new ObjectParameter("TODATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeLaoDong>("GetThongKeLaoDong", sYSTEMIDParameter, cAPDOParameter, gIATRICAPDOParameter, cONGDOANParameter, fROMDATEParameter, tODATEParameter);
        }
    
        public virtual ObjectResult<ListCongDoan> GetCongDoanKhTh(string systemId, string capDo, string giaTriCapDo, string congDoan, string fromDate, string toDate)
        {
            var systemIdParameter = systemId != null ?
                new ObjectParameter("systemId", systemId) :
                new ObjectParameter("systemId", typeof(string));
    
            var capDoParameter = capDo != null ?
                new ObjectParameter("capDo", capDo) :
                new ObjectParameter("capDo", typeof(string));
    
            var giaTriCapDoParameter = giaTriCapDo != null ?
                new ObjectParameter("giaTriCapDo", giaTriCapDo) :
                new ObjectParameter("giaTriCapDo", typeof(string));
    
            var congDoanParameter = congDoan != null ?
                new ObjectParameter("congDoan", congDoan) :
                new ObjectParameter("congDoan", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListCongDoan>("GetCongDoanKhTh", systemIdParameter, capDoParameter, giaTriCapDoParameter, congDoanParameter, fromDateParameter, toDateParameter);
        }
    }
}
