//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZEMP_SL_WC
    {
        public string SystemId { get; set; }
        public string Wrkct { get; set; }
        public System.DateTime Ngay { get; set; }
        public string CongDoan { get; set; }
        public Nullable<decimal> SoLuongLD { get; set; }
        public Nullable<decimal> NangSuat { get; set; }
        public Nullable<decimal> GioLamViec { get; set; }
        public Nullable<decimal> KeHoachGio { get; set; }
        public Nullable<decimal> KeHoachNgay { get; set; }
        public Nullable<decimal> ThucHienNgay { get; set; }
        public Nullable<decimal> ChenhLech { get; set; }
        public Nullable<decimal> DatKeHoach { get; set; }
        public Nullable<decimal> Gio01 { get; set; }
        public Nullable<decimal> Gio02 { get; set; }
        public Nullable<decimal> Gio03 { get; set; }
        public Nullable<decimal> Gio04 { get; set; }
        public Nullable<decimal> Gio05 { get; set; }
        public Nullable<decimal> Gio06 { get; set; }
        public Nullable<decimal> Gio07 { get; set; }
        public Nullable<decimal> Gio08 { get; set; }
        public Nullable<decimal> Gio09 { get; set; }
        public Nullable<decimal> Gio10 { get; set; }
        public Nullable<decimal> Gio11 { get; set; }
        public Nullable<decimal> Gio12 { get; set; }
        public Nullable<decimal> Gio13 { get; set; }
        public Nullable<decimal> Gio14 { get; set; }
        public Nullable<decimal> Gio15 { get; set; }
        public Nullable<decimal> Gio16 { get; set; }
        public Nullable<decimal> Gio17 { get; set; }
        public Nullable<decimal> Gio18 { get; set; }
        public Nullable<decimal> Gio19 { get; set; }
        public Nullable<decimal> Gio20 { get; set; }
        public Nullable<decimal> Gio21 { get; set; }
        public Nullable<decimal> Gio22 { get; set; }
        public Nullable<decimal> Gio23 { get; set; }
        public Nullable<decimal> Gio24 { get; set; }
        public Nullable<decimal> Tuan { get; set; }
        public Nullable<decimal> Thang { get; set; }
        public Nullable<decimal> Quy { get; set; }
        public Nullable<decimal> Nam { get; set; }
    }
}
