//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZEMP_LOG
    {
        public long ID { get; set; }
        public string SystemId { get; set; }
        public System.DateTime Ngay { get; set; }
        public string LogKey { get; set; }
        public string LogDescription { get; set; }
    }
}
