//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZEMP_CONGDOAN
    {
        public string SystemId { get; set; }
        public string CongDoan { get; set; }
        public string TenCongDoan { get; set; }
        public decimal Stt { get; set; }
    }
}
