//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZEMP_TK_KV
    {
        public string SystemId { get; set; }
        public System.DateTime Ngay { get; set; }
        public string KhuVuc { get; set; }
        public string CongDoan { get; set; }
        public Nullable<decimal> TongLaoDong { get; set; }
        public Nullable<decimal> ChuyenXanh { get; set; }
        public Nullable<decimal> ChuyenVang { get; set; }
        public Nullable<decimal> ChuyenDo { get; set; }
        public Nullable<decimal> VatTuKeHoach { get; set; }
        public Nullable<decimal> VatTuThucHien { get; set; }
        public Nullable<decimal> TaiSanKeHoach { get; set; }
        public Nullable<decimal> TaiSanThucHien { get; set; }
        public Nullable<decimal> NhanCongKeHoach { get; set; }
        public Nullable<decimal> NhanCongThucHien { get; set; }
        public Nullable<decimal> Tuan { get; set; }
        public Nullable<decimal> Thang { get; set; }
        public Nullable<decimal> Quy { get; set; }
        public Nullable<decimal> Nam { get; set; }
        public Nullable<decimal> TyGia { get; set; }
    }
}
