//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZEMP_CH
    {
        public string SystemId { get; set; }
        public string IdChuyen { get; set; }
        public string Xuong { get; set; }
        public string Wrkct { get; set; }
        public string KhuVuc { get; set; }
        public string Nganh { get; set; }
        public string MaChuyen { get; set; }
        public string TenChuyen { get; set; }
        public string QlChuyen { get; set; }
        public string CongDoan { get; set; }
        public string ZIACT { get; set; }
        public string IsNoColor { get; set; }
    }
}
