//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEMP.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZEMP_USER
    {
        public string SystemId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string HoTen { get; set; }
        public string ChucVu { get; set; }
        public string LastMode { get; set; }
        public string LastCapDo { get; set; }
        public string LastGiaTriCapDo { get; set; }
        public string LastCongDoan { get; set; }
        public string InActive { get; set; }
    }
}
