//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_CPTH
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public string ZYEAR { get; set; }
        public string ZMONTH { get; set; }
        public string ZWEEK { get; set; }
        public System.DateTime ZDATE { get; set; }
        public string CNTCD { get; set; }
        public string ZZCNT { get; set; }
        public string ZCHUYN { get; set; }
        public string ZWRKCT { get; set; }
        public string ZKHVUC { get; set; }
        public string ZNGANH { get; set; }
        public string ZCDOAN { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string MEINS { get; set; }
        public Nullable<decimal> DSOSX { get; set; }
        public Nullable<decimal> DSFOB { get; set; }
        public string WAERS { get; set; }
        public Nullable<decimal> DSOSX_USD { get; set; }
        public Nullable<decimal> DSFOB_USD { get; set; }
        public string WAERS_USD { get; set; }
        public Nullable<decimal> ZVTKH { get; set; }
        public Nullable<decimal> ZNCKH { get; set; }
        public Nullable<decimal> ZTSKH { get; set; }
        public Nullable<decimal> ZCLKH_SX { get; set; }
        public Nullable<decimal> ZCLKH_FOB { get; set; }
        public Nullable<decimal> ZVTTH { get; set; }
        public Nullable<decimal> ZNCTH { get; set; }
        public Nullable<decimal> ZTSTH { get; set; }
        public Nullable<decimal> ZCLTH_SX { get; set; }
        public Nullable<decimal> ZCLTH_FOB { get; set; }
        public string ERNAM { get; set; }
    }
}
