//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_COLOR_CDOAN
    {
        public string CDOAN { get; set; }
        public string COLORCODE { get; set; }
        public string COLORCODEKH { get; set; }
    }
}
