//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_PHAN_QUYEN
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public string Username { get; set; }
        public string CapDo { get; set; }
        public string GiaTri { get; set; }
        public string DGCapDo { get; set; }
        public string DGGiaTri { get; set; }
        public string Ghi_chu { get; set; }
    }
}
