//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_SLSX_CHUYEN_NGAY
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public System.DateTime PDATUM { get; set; }
        public string ZZCNT { get; set; }
        public string CNTCD { get; set; }
        public string NGANH { get; set; }
        public string KHVUC { get; set; }
        public string WRKCT { get; set; }
        public string ZXUONG { get; set; }
        public string CHUYN { get; set; }
        public string CDOAN { get; set; }
        public string LTEXT { get; set; }
        public string DAURA_WC { get; set; }
        public string DAURA_KV { get; set; }
        public string COLOR_CH { get; set; }
        public string ZYEAR { get; set; }
        public string ZMONTH { get; set; }
        public string ZWEEK { get; set; }
        public Nullable<decimal> SLLD { get; set; }
        public Nullable<decimal> SLLD_FULL { get; set; }
        public Nullable<decimal> NSUAT { get; set; }
        public Nullable<decimal> LK_NGAY { get; set; }
        public Nullable<decimal> GIO01 { get; set; }
        public Nullable<decimal> GIO02 { get; set; }
        public Nullable<decimal> GIO03 { get; set; }
        public Nullable<decimal> GIO04 { get; set; }
        public Nullable<decimal> GIO05 { get; set; }
        public Nullable<decimal> GIO06 { get; set; }
        public Nullable<decimal> GIO07 { get; set; }
        public Nullable<decimal> GIO08 { get; set; }
        public Nullable<decimal> GIO09 { get; set; }
        public Nullable<decimal> GIO10 { get; set; }
        public Nullable<decimal> GIO11 { get; set; }
        public Nullable<decimal> GIO12 { get; set; }
        public Nullable<decimal> GIO13 { get; set; }
        public Nullable<decimal> GIO14 { get; set; }
        public Nullable<decimal> GIO15 { get; set; }
        public Nullable<decimal> GIO16 { get; set; }
        public Nullable<decimal> GIO17 { get; set; }
        public Nullable<decimal> GIO18 { get; set; }
        public Nullable<decimal> GIO19 { get; set; }
        public Nullable<decimal> GIO20 { get; set; }
        public Nullable<decimal> GIO21 { get; set; }
        public Nullable<decimal> GIO22 { get; set; }
        public Nullable<decimal> GIO23 { get; set; }
        public Nullable<decimal> GIO24 { get; set; }
        public string MEINS { get; set; }
        public Nullable<System.DateTime> LSTDATE { get; set; }
    }
}
