//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_SLSX_CHUYEN_TUAN
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public string ZYEAR { get; set; }
        public string ZWEEK { get; set; }
        public string ZZCNT { get; set; }
        public string CNTCD { get; set; }
        public string NGANH { get; set; }
        public string KHVUC { get; set; }
        public string WRKCT { get; set; }
        public string XUONG { get; set; }
        public string CHUYN { get; set; }
        public string CDOAN { get; set; }
        public string LTEXT { get; set; }
        public string DAURA_WC { get; set; }
        public string DAURA_KV { get; set; }
        public Nullable<decimal> LK_TUAN { get; set; }
        public Nullable<decimal> NSLDBQ { get; set; }
        public Nullable<decimal> NGAY01 { get; set; }
        public Nullable<decimal> NSLD01 { get; set; }
        public Nullable<decimal> NGAY02 { get; set; }
        public Nullable<decimal> NSLD02 { get; set; }
        public Nullable<decimal> NGAY03 { get; set; }
        public Nullable<decimal> NSLD03 { get; set; }
        public Nullable<decimal> NGAY04 { get; set; }
        public Nullable<decimal> NSLD04 { get; set; }
        public Nullable<decimal> NGAY05 { get; set; }
        public Nullable<decimal> NSLD05 { get; set; }
        public Nullable<decimal> NGAY06 { get; set; }
        public Nullable<decimal> NSLD06 { get; set; }
        public Nullable<decimal> NGAY07 { get; set; }
        public Nullable<decimal> NSLD07 { get; set; }
        public string MEINS { get; set; }
        public Nullable<System.DateTime> LSTDATE { get; set; }
        public System.DateTime FRSTDAYWK { get; set; }
    }
}
