//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_SLSX_CHUYEN_THANG
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public string ZYEAR { get; set; }
        public string ZMONTH { get; set; }
        public string ZZCNT { get; set; }
        public string CNTCD { get; set; }
        public string NGANH { get; set; }
        public string KHVUC { get; set; }
        public string WRKCT { get; set; }
        public string XUONG { get; set; }
        public string CHUYN { get; set; }
        public string CDOAN { get; set; }
        public string LTEXT { get; set; }
        public string DAURA_WC { get; set; }
        public string DAURA_KV { get; set; }
        public Nullable<decimal> LK_THANG { get; set; }
        public Nullable<decimal> NSLDBQ { get; set; }
        public Nullable<decimal> NGAY01 { get; set; }
        public Nullable<decimal> NSLD01 { get; set; }
        public Nullable<decimal> NGAY02 { get; set; }
        public Nullable<decimal> NSLD02 { get; set; }
        public Nullable<decimal> NGAY03 { get; set; }
        public Nullable<decimal> NSLD03 { get; set; }
        public Nullable<decimal> NGAY04 { get; set; }
        public Nullable<decimal> NSLD04 { get; set; }
        public Nullable<decimal> NGAY05 { get; set; }
        public Nullable<decimal> NSLD05 { get; set; }
        public Nullable<decimal> NGAY06 { get; set; }
        public Nullable<decimal> NSLD06 { get; set; }
        public Nullable<decimal> NGAY07 { get; set; }
        public Nullable<decimal> NSLD07 { get; set; }
        public Nullable<decimal> NGAY08 { get; set; }
        public Nullable<decimal> NSLD08 { get; set; }
        public Nullable<decimal> NGAY09 { get; set; }
        public Nullable<decimal> NSLD09 { get; set; }
        public Nullable<decimal> NGAY10 { get; set; }
        public Nullable<decimal> NSLD10 { get; set; }
        public Nullable<decimal> NGAY11 { get; set; }
        public Nullable<decimal> NSLD11 { get; set; }
        public Nullable<decimal> NGAY12 { get; set; }
        public Nullable<decimal> NSLD12 { get; set; }
        public Nullable<decimal> NGAY13 { get; set; }
        public Nullable<decimal> NSLD13 { get; set; }
        public Nullable<decimal> NGAY14 { get; set; }
        public Nullable<decimal> NSLD14 { get; set; }
        public Nullable<decimal> NGAY15 { get; set; }
        public Nullable<decimal> NSLD15 { get; set; }
        public Nullable<decimal> NGAY16 { get; set; }
        public Nullable<decimal> NSLD16 { get; set; }
        public Nullable<decimal> NGAY17 { get; set; }
        public Nullable<decimal> NSLD17 { get; set; }
        public Nullable<decimal> NGAY18 { get; set; }
        public Nullable<decimal> NSLD18 { get; set; }
        public Nullable<decimal> NGAY19 { get; set; }
        public Nullable<decimal> NSLD19 { get; set; }
        public Nullable<decimal> NGAY20 { get; set; }
        public Nullable<decimal> NSLD20 { get; set; }
        public Nullable<decimal> NGAY21 { get; set; }
        public Nullable<decimal> NSLD21 { get; set; }
        public Nullable<decimal> NGAY22 { get; set; }
        public Nullable<decimal> NSLD22 { get; set; }
        public Nullable<decimal> NGAY23 { get; set; }
        public Nullable<decimal> NSLD23 { get; set; }
        public Nullable<decimal> NGAY24 { get; set; }
        public Nullable<decimal> NSLD24 { get; set; }
        public Nullable<decimal> NGAY25 { get; set; }
        public Nullable<decimal> NSLD25 { get; set; }
        public Nullable<decimal> NGAY26 { get; set; }
        public Nullable<decimal> NSLD26 { get; set; }
        public Nullable<decimal> NGAY27 { get; set; }
        public Nullable<decimal> NSLD27 { get; set; }
        public Nullable<decimal> NGAY28 { get; set; }
        public Nullable<decimal> NSLD28 { get; set; }
        public Nullable<decimal> NGAY29 { get; set; }
        public Nullable<decimal> NSLD29 { get; set; }
        public Nullable<decimal> NGAY30 { get; set; }
        public Nullable<decimal> NSLD30 { get; set; }
        public Nullable<decimal> NGAY31 { get; set; }
        public Nullable<decimal> NSLD31 { get; set; }
        public string MEINS { get; set; }
        public Nullable<System.DateTime> LSTDATE { get; set; }
    }
}
