//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_SANLUONG_ONLINE_TEMP
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public System.DateTime NGAY { get; set; }
        public string ZZCNT { get; set; }
        public string CNTCD { get; set; }
        public Nullable<decimal> SLLD { get; set; }
        public Nullable<decimal> NSUAT { get; set; }
        public Nullable<decimal> GIOLV { get; set; }
        public Nullable<decimal> KHGIO { get; set; }
        public Nullable<decimal> KHNGAY { get; set; }
        public Nullable<decimal> THNGAY { get; set; }
        public Nullable<decimal> CHLECH { get; set; }
        public Nullable<decimal> DATKH { get; set; }
        public string MEINS { get; set; }
        public Nullable<decimal> GIO01 { get; set; }
        public Nullable<decimal> GIO02 { get; set; }
        public Nullable<decimal> GIO03 { get; set; }
        public Nullable<decimal> GIO04 { get; set; }
        public Nullable<decimal> GIO05 { get; set; }
        public Nullable<decimal> GIO06 { get; set; }
        public Nullable<decimal> GIO07 { get; set; }
        public Nullable<decimal> GIO08 { get; set; }
        public Nullable<decimal> GIO09 { get; set; }
        public Nullable<decimal> GIO10 { get; set; }
        public Nullable<decimal> GIO11 { get; set; }
        public Nullable<decimal> GIO12 { get; set; }
        public Nullable<decimal> GIO13 { get; set; }
        public Nullable<decimal> GIO14 { get; set; }
        public Nullable<decimal> GIO15 { get; set; }
        public Nullable<decimal> GIO16 { get; set; }
        public Nullable<decimal> GIO17 { get; set; }
        public Nullable<decimal> GIO18 { get; set; }
        public Nullable<decimal> GIO19 { get; set; }
        public Nullable<decimal> GIO20 { get; set; }
        public Nullable<decimal> GIO21 { get; set; }
        public Nullable<decimal> GIO22 { get; set; }
        public Nullable<decimal> GIO23 { get; set; }
        public Nullable<decimal> GIO24 { get; set; }
        public string ZIACT { get; set; }
        public Nullable<decimal> gio_dalam { get; set; }
    }
}
