//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_SLKH_WC
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public string NAM { get; set; }
        public string THANG { get; set; }
        public string KHVUC { get; set; }
        public string WRKCT { get; set; }
        public string CNTCD { get; set; }
        public System.DateTime FIRSTDAY { get; set; }
        public string NGANH { get; set; }
        public string XUONG { get; set; }
        public string CDOAN { get; set; }
        public string DONVI { get; set; }
        public Nullable<decimal> SLTONG { get; set; }
        public Nullable<decimal> NGAY01 { get; set; }
        public Nullable<decimal> NGAY02 { get; set; }
        public Nullable<decimal> NGAY03 { get; set; }
        public Nullable<decimal> NGAY04 { get; set; }
        public Nullable<decimal> NGAY05 { get; set; }
        public Nullable<decimal> NGAY06 { get; set; }
        public Nullable<decimal> NGAY07 { get; set; }
        public Nullable<decimal> NGAY08 { get; set; }
        public Nullable<decimal> NGAY09 { get; set; }
        public Nullable<decimal> NGAY10 { get; set; }
        public Nullable<decimal> NGAY11 { get; set; }
        public Nullable<decimal> NGAY12 { get; set; }
        public Nullable<decimal> NGAY13 { get; set; }
        public Nullable<decimal> NGAY14 { get; set; }
        public Nullable<decimal> NGAY15 { get; set; }
        public Nullable<decimal> NGAY16 { get; set; }
        public Nullable<decimal> NGAY17 { get; set; }
        public Nullable<decimal> NGAY18 { get; set; }
        public Nullable<decimal> NGAY19 { get; set; }
        public Nullable<decimal> NGAY20 { get; set; }
        public Nullable<decimal> NGAY21 { get; set; }
        public Nullable<decimal> NGAY22 { get; set; }
        public Nullable<decimal> NGAY23 { get; set; }
        public Nullable<decimal> NGAY24 { get; set; }
        public Nullable<decimal> NGAY25 { get; set; }
        public Nullable<decimal> NGAY26 { get; set; }
        public Nullable<decimal> NGAY27 { get; set; }
        public Nullable<decimal> NGAY28 { get; set; }
        public Nullable<decimal> NGAY29 { get; set; }
        public Nullable<decimal> NGAY30 { get; set; }
        public Nullable<decimal> NGAY31 { get; set; }
    }
}
