//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_SLLD_CHUYEN
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public System.DateTime PDATUM { get; set; }
        public string ZZCNT { get; set; }
        public string XUONG { get; set; }
        public string WRKCT { get; set; }
        public string KHVUC { get; set; }
        public string NGANH { get; set; }
        public decimal SLLD { get; set; }
    }
}
