//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_TONGLD
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public System.DateTime PDATUM { get; set; }
        public string CAPDO { get; set; }
        public string BOPHAN { get; set; }
        public Nullable<decimal> TONGLD { get; set; }
        public string ZYEAR { get; set; }
        public string ZMONTH { get; set; }
        public string ZWEEK { get; set; }
    }
}
