//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbsGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_ZQLSX
    {
        public string MANDT { get; set; }
        public string SYSID { get; set; }
        public string ZZCNT { get; set; }
        public string NGANH { get; set; }
        public string KHVUC { get; set; }
        public string WRKCT { get; set; }
        public string XUONG { get; set; }
        public string CHUYN { get; set; }
        public string TNNG { get; set; }
        public string TNKV { get; set; }
        public string TNWC { get; set; }
        public string TNXG { get; set; }
        public string TNCH { get; set; }
        public string QLCH { get; set; }
        public string QLWC { get; set; }
        public string QLKV { get; set; }
        public string CDOAN { get; set; }
        public string CH_CHAT { get; set; }
        public string DAURA_WC { get; set; }
        public string DAURA_KV { get; set; }
        public string ZGROUP { get; set; }
        public string GIACONG { get; set; }
        public string MUANGOAI { get; set; }
        public string ZDB_CH { get; set; }
        public string ZGCNG { get; set; }
        public string ZIACT { get; set; }
        public string TENCD { get; set; }
        public string NCOLOR { get; set; }
    }
}
